### ISSUE TITLE
Isometric is cool - but broken!

### ISSUE THREAD

**Issue by jakebrown58** [jakebrown58/GravitySimulator#20]
Follow and stuff doesn't work

**Comment by brb1031** [comment]
Follow works in PR #36 , stuff still doesn't.

**Comment by jakebrown58** [comment]
merged the PR - but this issue still persists.

it was an excellent first step.

the look and feel of the mouse-move-to-change-the-view is still clunky, and it's very choppy when looking at it flat which sucks, because that's the best part.

**Comment by brb1031** [comment]
I was thinking right click and drag for changing viewangle up and down (and side to side).  Do you recommend an approach for capturing this/ or if this is what we want.

**Comment by jakebrown58** [comment]
that's not bad as an interim, though I think the feature is low on the discover-ability scale.
right now - the always-on is kind of annoying too.   

ultimately - i'd rather have a 'camera' mode where the mouse controls the orientation of a camera on move, and maybe in that view supports 'wasd' for zooming and scrolling, and has support for fixate on an XYZ coordinate, rather than a specific particle.

in that vein, it might be better to just work toward the end goal rather than spend time on intermediate steps that don't take us to where we're headed.

**Comment by brb1031** [comment]
Well, any but the default mode is not too discoverable right now.  Maybe a momentary (as opposed to toggle) could show a cheat sheet.  Or similar could be added while paused?

Holding right mouse to rotate view seems natural to me, but maybe not to others.  KSP, 3d plotting programs, where you manipulate an object, are done this way.  FPS's are done with mouse look always on.  I also keep mouse wheeling, expecting it to zoom in and out.  But I am anecdote.

**Comment by jakebrown58** [comment]
good thoughts.

i'm thinking a FPS approach - and your point is valid about low discover score right now.

**Comment by brb1031** [comment]
Do we want to BE the rocket?  Do we want to fly through space?  Yeah, probably.

**Comment by jakebrown58** [comment]
we want to be able to land the rocket on a planet.   and then go somewhere else with it.  and have the rocket blow up if we have it land on the planet too hard.

**Comment by brb1031** [comment]
That sounds like a pretty good idea.

**Comment by jakebrown58** [comment]
and then look out the window of the rocket and see the moon orbiting overhead while we're parked on another moon and then jupiter comes along and we're like, 'wow jupiter is really big'.

**Comment by brb1031** [comment]
Fact.

**Comment by brb1031** [comment]
PR #40 and #42 address.

**Comment by jakebrown58** [comment]
This issue is obsolete based on the fluid viewport changes.
