### ISSUE TITLE
Master has broken collissions in it again

### ISSUE THREAD

**Issue by jakebrown58** [jakebrown58/GravitySimulator#32]
Vector3d was supposed to be reverted - but it's in master again.

**Comment by brb1031** [comment]
Vector3d buffer fixes this, but that is way ... um downstream?  Ahead?

**Comment by jakebrown58** [comment]
well, how did master get Vectors again?

**Comment by jakebrown58** [comment]
the 'r' key collissions are broken in Main.
they're also broken in particle-position-encapsulation

**Comment by brb1031** [comment]
Hold up, had a look.  It was re-broken when we rewinded.  Master from yesterday has the same bug.  (I didn't re-implement a fix since it's already downstream in another PR).

**Comment by brb1031** [comment]
Would it be worthwhile for me to clean up these PR's?
