### ISSUE TITLE
Frame Rate in HUD does not match actual frame rate

### ISSUE THREAD

**Issue by brb1031** [jakebrown58/GravitySimulator#33]
When looking at the asteroid belt view with HUD up, (via "C", "R"), the calculated fps will sometimes be as low as 0-2, while the display is obviously updating much more frequently than this.

**Comment by jakebrown58** [comment]
probably a minor reset issue where frames count since you hit 'r', but time counts since you started the simluation.

**Comment by jakebrown58** [comment]
Fixed by #41
