### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by brb1031** [jakebrown58/GravitySimulator#43]
Linting.  We should do it.

**Comment by brb1031** [comment]
1. Sublime install package sublinter.
2. Install software package "node" if not installed.  (Either brew (OSX) or windows install from nodejs.org)
3. Then follow directions here: https://packagecontrol.io/packages/JSHint to install jshint.  Or at shell prompt:

 `npm install -g jshint`
4. Sublime install package sublinter-jshint

5. Control - J for all the fun.

**Comment by jakebrown58** [comment]
closed.
