### ISSUE TITLE
Host a deployable demo for non-developers

### ISSUE THREAD

**Issue by brb1031** [jakebrown58/GravitySimulator#44]

**Comment by jakebrown58** [comment]
yes!

**Comment by mcw0933** [comment]
https://rawgit.com/jakebrown58/GravitySimulator/master/particles.html

**Comment by mcw0933** [comment]
Alternative: 
http://htmlpreview.github.io/?https://github.com/jakebrown58/GravitySimulator/blob/master/particles.html

From: http://stackoverflow.com/questions/6551446/can-i-run-html-files-directly-from-github-instead-of-just-viewing-their-source
